package com.xworkz.spring.boot;

import org.springframework.context.ApplicationContext;
import org.springframework.context.annotation.AnnotationConfigApplicationContext;

import com.xworkz.spring.configuration.SpringConfiguration;
import com.xworkz.spring.entity.AirEntity;
import com.xworkz.spring.entity.Ant;
import com.xworkz.spring.entity.Fruit;
import com.xworkz.spring.entity.Gate;
import com.xworkz.spring.entity.Human;
import com.xworkz.spring.entity.Laptop;
import com.xworkz.spring.entity.PartyEntity;

public class SpringBoot {

	public static void main(String args[]) {

		ApplicationContext context = new AnnotationConfigApplicationContext(SpringConfiguration.class);
		// PartyEntity bean = context.getBean(PartyEntity.class);
		// bean.partyHard();
		System.out.println(context.getBean(PartyEntity.class));
		System.out.println(context.getBean(AirEntity.class).hashCode());
		System.out.println(context.getBean(Ant.class).hashCode());
		System.out.println(context.getBean(Fruit.class).hashCode());
		System.out.println(context.getBean(Gate.class).hashCode());
		System.out.println(context.getBean(Human.class).hashCode());
		System.out.println(context.getBean(Laptop.class).hashCode());
		System.out.println("playerName" + context.getBean("playerName", String.class).hashCode());
		System.out.println(context.getBean("playerName1", String.class).hashCode());
		System.out.println(context.getBean("playerName2", String.class).hashCode());
		System.out.println(context.getBean("playerName3", String.class).hashCode());
		System.out.println(context.getBean("playerName4", String.class).hashCode());
		System.out.println(context.getBean("playerName5", String.class).hashCode());
		System.out.println(context.getBean("playerName6", String.class).hashCode());
		System.out.println(context.getBean("playerName7", String.class).hashCode());
		System.out.println(context.getBean("playerName8", String.class).hashCode());
		System.out.println(context.getBean("playerName9", String.class).hashCode());
		System.out.println(context.getBean("playerName10", String.class).hashCode());
		System.out.println("playerName11" + context.getBean("playerName11", String.class).hashCode());
		System.out.println("name:" + context.getBean("name", String.class).hashCode());
		System.out.println(context.getBean("name1", String.class).hashCode());
		System.out.println(context.getBean("name2", String.class).hashCode());
		System.out.println(context.getBean("name3", String.class).hashCode());
		System.out.println(context.getBean("name4", String.class).hashCode());
		System.out.println(context.getBean("name5", String.class).hashCode());
		System.out.println(context.getBean("name6", String.class).hashCode());
		System.out.println(context.getBean("name7", String.class).hashCode());
		System.out.println(context.getBean("name8", String.class).hashCode());
		System.out.println("name9:" + context.getBean("name9", String.class).hashCode());
		System.out.println("--------Bikes Starts ---------------------");
		System.out.println("HashCode of bike1:" + context.getBean("bike1", String.class).hashCode());
		System.out.println("HashCode of bike2:" + context.getBean("bike2", String.class).hashCode());
		System.out.println("HashCode of bike3:" + context.getBean("bike3", String.class).hashCode());
		System.out.println("HashCode of bike4:" + context.getBean("bike4", String.class).hashCode());
		System.out.println("HashCode of bike5:" + context.getBean("bike5", String.class).hashCode());
		System.out.println("HashCode of bike6:" + context.getBean("bike6", String.class).hashCode());
		System.out.println("HashCode of bike7:" + context.getBean("bike7", String.class).hashCode());
		System.out.println("HashCode of bike8:" + context.getBean("bike8", String.class).hashCode());
		System.out.println("HashCode of bike9:" + context.getBean("bike9", String.class).hashCode());
		System.out.println("HashCode of bike10:" + context.getBean("bike10", String.class).hashCode());
		System.out.println("HashCode of bike11:" + context.getBean("bike11", String.class).hashCode());
		System.out.println("HashCode of bike12:" + context.getBean("bike12", String.class).hashCode());
		System.out.println("HashCode of bike13:" + context.getBean("bike13", String.class).hashCode());
		System.out.println("HashCode of bike14:" + context.getBean("bike14", String.class).hashCode());
		System.out.println("HashCode of bike15:" + context.getBean("bike15", String.class).hashCode());
		System.out.println("HashCode of bike16:" + context.getBean("bike16", String.class).hashCode());
		System.out.println("HashCode of bike17:" + context.getBean("bike17", String.class).hashCode());
		System.out.println("HashCode of bike18:" + context.getBean("bike18", String.class).hashCode());
		System.out.println("HashCode of bike19:" + context.getBean("bike19", String.class).hashCode());
		System.out.println("HashCode of bike20:" + context.getBean("bike20", String.class).hashCode());
		System.out.println("HashCode of bike21:" + context.getBean("bike21", String.class).hashCode());
		System.out.println("HashCode of bike22:" + context.getBean("bike22", String.class).hashCode());
		System.out.println("HashCode of bike23:" + context.getBean("bike23", String.class).hashCode());
		System.out.println("HashCode of bike24:" + context.getBean("bike24", String.class).hashCode());
		System.out.println("HashCode of bike25:" + context.getBean("bike25", String.class).hashCode());
		System.out.println("HashCode of bike26:" + context.getBean("bike26", String.class).hashCode());
		System.out.println("HashCode of bike27:" + context.getBean("bike27", String.class).hashCode());
		System.out.println("HashCode of bike28:" + context.getBean("bike28", String.class).hashCode());
		System.out.println("HashCode of bike29:" + context.getBean("bike29", String.class).hashCode());
		System.out.println("HashCode of bike30:" + context.getBean("bike30", String.class).hashCode());
		System.out.println("HashCode of bike31:" + context.getBean("bike31", String.class).hashCode());
		System.out.println("HashCode of bike32:" + context.getBean("bike32", String.class).hashCode());
		System.out.println("HashCode of bike33:" + context.getBean("bike33", String.class).hashCode());
		System.out.println("HashCode of bike34:" + context.getBean("bike34", String.class).hashCode());
		System.out.println("HashCode of bike35:" + context.getBean("bike35", String.class).hashCode());
		System.out.println("HashCode of bike36:" + context.getBean("bike36", String.class).hashCode());
		System.out.println("HashCode of bike37:" + context.getBean("bike37", String.class).hashCode());
		System.out.println("HashCode of bike38:" + context.getBean("bike38", String.class).hashCode());
		System.out.println("HashCode of bike39:" + context.getBean("bike39", String.class).hashCode());
		System.out.println("HashCode of bike40:" + context.getBean("bike40", String.class).hashCode());
		System.out.println("HashCode of bike41:" + context.getBean("bike41", String.class).hashCode());
		System.out.println("HashCode of bike42:" + context.getBean("bike42", String.class).hashCode());
		System.out.println("HashCode of bike43:" + context.getBean("bike43", String.class).hashCode());
		System.out.println("HashCode of bike44:" + context.getBean("bike44", String.class).hashCode());
		System.out.println("HashCode of bike45:" + context.getBean("bike45", String.class).hashCode());
		System.out.println("HashCode of bike46:" + context.getBean("bike46", String.class).hashCode());
		System.out.println("HashCode of bike47:" + context.getBean("bike47", String.class).hashCode());
		System.out.println("HashCode of bike48:" + context.getBean("bike48", String.class).hashCode());
		System.out.println("HashCode of bike49:" + context.getBean("bike49", String.class).hashCode());
		System.out.println("HashCode of bike50:" + context.getBean("bike50", String.class).hashCode());

		System.out.println("===========Car Starts===============");
		System.out.println("car:" + context.getBean("car", String.class).hashCode());
		System.out.println(context.getBean("car1", String.class).hashCode());
		System.out.println(context.getBean("car2", String.class).hashCode());
		System.out.println(context.getBean("car3", String.class).hashCode());
		System.out.println(context.getBean("car4", String.class).hashCode());
		System.out.println(context.getBean("car5", String.class).hashCode());
		System.out.println(context.getBean("car6", String.class).hashCode());
		System.out.println(context.getBean("car7", String.class).hashCode());
		System.out.println(context.getBean("car8", String.class).hashCode());
		System.out.println(context.getBean("car9", String.class).hashCode());
		System.out.println("====================Car-10=========");
		System.out.println("car10:" + context.getBean("car10", String.class).hashCode());
		System.out.println(context.getBean("car11", String.class).hashCode());
		System.out.println(context.getBean("car12", String.class).hashCode());
		System.out.println(context.getBean("car13", String.class).hashCode());
		System.out.println(context.getBean("car14", String.class).hashCode());
		System.out.println(context.getBean("car15", String.class).hashCode());
		System.out.println(context.getBean("car16", String.class).hashCode());
		System.out.println(context.getBean("car17", String.class).hashCode());
		System.out.println(context.getBean("car18", String.class).hashCode());
		System.out.println(context.getBean("car19", String.class).hashCode());
		System.out.println("---------------Car-20-----------");
		System.out.println("car20:" + context.getBean("car20", String.class).hashCode());
		System.out.println(context.getBean("car21", String.class).hashCode());
		System.out.println(context.getBean("car22", String.class).hashCode());
		System.out.println(context.getBean("car23", String.class).hashCode());
		System.out.println(context.getBean("car24", String.class).hashCode());
		System.out.println(context.getBean("car25", String.class).hashCode());
		System.out.println(context.getBean("car26", String.class).hashCode());
		System.out.println(context.getBean("car27", String.class).hashCode());
		System.out.println(context.getBean("car28", String.class).hashCode());
		System.out.println(context.getBean("car29", String.class).hashCode());
		System.out.println("============Car-30===========");
		System.out.println("car30:" + context.getBean("car30", String.class).hashCode());
		System.out.println(context.getBean("car31", String.class).hashCode());
		System.out.println(context.getBean("car32", String.class).hashCode());
		System.out.println(context.getBean("car33", String.class).hashCode());
		System.out.println(context.getBean("car34", String.class).hashCode());
		System.out.println(context.getBean("car35", String.class).hashCode());
		System.out.println(context.getBean("car36", String.class).hashCode());
		System.out.println(context.getBean("car37", String.class).hashCode());
		System.out.println(context.getBean("car38", String.class).hashCode());
		System.out.println(context.getBean("car39", String.class).hashCode());
		System.out.println("----------------Car-40--------");
		System.out.println("car40:" + context.getBean("car40", String.class).hashCode());
		System.out.println(context.getBean("car41", String.class).hashCode());
		System.out.println(context.getBean("car42", String.class).hashCode());
		System.out.println(context.getBean("car43", String.class).hashCode());
		System.out.println(context.getBean("car44", String.class).hashCode());
		System.out.println(context.getBean("car45", String.class).hashCode());
		System.out.println(context.getBean("car46", String.class).hashCode());
		System.out.println(context.getBean("car47", String.class).hashCode());
		System.out.println(context.getBean("car48", String.class).hashCode());
		System.out.println(context.getBean("car49", String.class).hashCode());
		System.out.println("-------------------Car-50-----------------");
		System.out.println("car50:" + context.getBean("car50", String.class).hashCode());
		System.out.println(context.getBean("car51", String.class).hashCode());
		System.out.println(context.getBean("car52", String.class).hashCode());
		System.out.println(context.getBean("car53", String.class).hashCode());
		System.out.println(context.getBean("car54", String.class).hashCode());
		System.out.println(context.getBean("car55", String.class).hashCode());
		System.out.println(context.getBean("car56", String.class).hashCode());
		System.out.println(context.getBean("car57", String.class).hashCode());
		System.out.println(context.getBean("car58", String.class).hashCode());
		System.out.println(context.getBean("car59", String.class).hashCode());
		System.out.println(context.getBean("car60", String.class).hashCode());
		System.out.println("========Car-61=======");
		System.out.println("car61:" + context.getBean("car61", String.class).hashCode());
		System.out.println("city1:" + context.getBean("city1", String.class).hashCode());
		System.out.println("city2:" + context.getBean("city2", String.class).hashCode());
		System.out.println("city3:" + context.getBean("city3", String.class).hashCode());
		System.out.println("city4:" + context.getBean("city4", String.class).hashCode());
		System.out.println("city5:" + context.getBean("city5", String.class).hashCode());
		System.out.println("city6:" + context.getBean("city6", String.class).hashCode());
		System.out.println("city7:" + context.getBean("city7", String.class).hashCode());
		System.out.println("city8:" + context.getBean("city8", String.class).hashCode());
		System.out.println("city9:" + context.getBean("city9", String.class).hashCode());
		System.out.println("city10:" + context.getBean("city10", String.class).hashCode());
		System.out.println("city11:" + context.getBean("city11", String.class).hashCode());
		System.out.println("city12:" + context.getBean("city12", String.class).hashCode());
		System.out.println("city13:" + context.getBean("city13", String.class).hashCode());
		System.out.println("------------------------------");
		System.out.println("city14:" + context.getBean("city14", String.class).hashCode());
		System.out.println("city15:" + context.getBean("city15", String.class).hashCode());
		System.out.println("city16:" + context.getBean("city16", String.class).hashCode());
		System.out.println("city17:" + context.getBean("city17", String.class).hashCode());
		System.out.println("city18:" + context.getBean("city18", String.class).hashCode());
		System.out.println("city19:" + context.getBean("city19", String.class).hashCode());
		System.out.println("city20:" + context.getBean("city20", String.class).hashCode());
		System.out.println("city21:" + context.getBean("city21", String.class).hashCode());
		System.out.println("city22:" + context.getBean("city22", String.class).hashCode());
		System.out.println("city23:" + context.getBean("city23", String.class).hashCode());
		System.out.println("city24:" + context.getBean("city24", String.class).hashCode());
		System.out.println("city25:" + context.getBean("city25", String.class).hashCode());
		System.out.println("city26:" + context.getBean("city26", String.class).hashCode());
		System.out.println("----++++++++++++++++++++----------");
		System.out.println("city27:" + context.getBean("city27", String.class).hashCode());
		System.out.println("city28:" + context.getBean("city28", String.class).hashCode());
		System.out.println("city29:" + context.getBean("city29", String.class).hashCode());
		System.out.println("city30:" + context.getBean("city30", String.class).hashCode());
		System.out.println("city31:" + context.getBean("city31", String.class).hashCode());
		System.out.println("city32:" + context.getBean("city32", String.class).hashCode());
		System.out.println("city33:" + context.getBean("city33", String.class).hashCode());
		System.out.println("city34:" + context.getBean("city34", String.class).hashCode());
		System.out.println("city35:" + context.getBean("city35", String.class).hashCode());
		System.out.println("city36:" + context.getBean("city36", String.class).hashCode());
		System.out.println("city37:" + context.getBean("city37", String.class).hashCode());
		System.out.println("city38:" + context.getBean("city38", String.class).hashCode());
		System.out.println("city39:" + context.getBean("city39", String.class).hashCode());
		System.out.println("city40:" + context.getBean("city40", String.class).hashCode());
		System.out.println("city41:" + context.getBean("city41", String.class).hashCode());

		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println("----------------Number Starts---------------------");
		System.out.println("number11:" + context.getBean("number11", String.class).hashCode());
		System.out.println(context.getBean("number12", String.class).hashCode());
		System.out.println(context.getBean("number13", String.class).hashCode());
		System.out.println(context.getBean("number14", String.class).hashCode());
		System.out.println(context.getBean("number15", String.class).hashCode());
		System.out.println(context.getBean("number16", String.class).hashCode());
		System.out.println(context.getBean("number17", String.class).hashCode());
		System.out.println(context.getBean("number18", String.class).hashCode());
		System.out.println(context.getBean("number19", String.class).hashCode());
		System.out.println("number20 :" + context.getBean("number20", String.class).hashCode());
		System.out.println(context.getBean("number21", String.class).hashCode());
		System.out.println(context.getBean("number22", String.class).hashCode());
		System.out.println(context.getBean("number23", String.class).hashCode());
		System.out.println(context.getBean("number24", String.class).hashCode());
		System.out.println(context.getBean("number25", String.class).hashCode());
		System.out.println(context.getBean("number26", String.class).hashCode());
		System.out.println(context.getBean("number27", String.class).hashCode());
		System.out.println(context.getBean("number28", String.class).hashCode());
		System.out.println(context.getBean("number29", String.class).hashCode());
		System.out.println("number30:" + context.getBean("number30", String.class).hashCode());
		System.out.println(context.getBean("number31", String.class).hashCode());
		System.out.println(context.getBean("number32", String.class).hashCode());
		System.out.println(context.getBean("number33", String.class).hashCode());
		System.out.println(context.getBean("number34", String.class).hashCode());
		System.out.println(context.getBean("number35", String.class).hashCode());
		System.out.println(context.getBean("number36", String.class).hashCode());
		System.out.println(context.getBean("number37", String.class).hashCode());
		System.out.println(context.getBean("number38", String.class).hashCode());
		System.out.println(context.getBean("number39", String.class).hashCode());
		System.out.println("number40 :" + context.getBean("number40", String.class).hashCode());
		System.out.println(context.getBean("number41", String.class).hashCode());
		System.out.println(context.getBean("number42", String.class).hashCode());
		System.out.println(context.getBean("number43", String.class).hashCode());
		System.out.println(context.getBean("number44", String.class).hashCode());
		System.out.println(context.getBean("number45", String.class).hashCode());
		System.out.println(context.getBean("number46", String.class).hashCode());
		System.out.println(context.getBean("number47", String.class).hashCode());
		System.out.println(context.getBean("number48", String.class).hashCode());
		System.out.println(context.getBean("number49", String.class).hashCode());
		System.out.println("number50:" + context.getBean("number50", String.class).hashCode());
		System.out.println(context.getBean("number51", String.class).hashCode());
		System.out.println(context.getBean("number52", String.class).hashCode());
		System.out.println(context.getBean("number53", String.class).hashCode());
		System.out.println(context.getBean("number54", String.class).hashCode());
		System.out.println(context.getBean("number55", String.class).hashCode());
		System.out.println(context.getBean("number56", String.class).hashCode());
		System.out.println(context.getBean("number57", String.class).hashCode());
		System.out.println(context.getBean("number58", String.class).hashCode());
		System.out.println(context.getBean("number59", String.class).hashCode());
		System.out.println("number60:" + context.getBean("number60", String.class).hashCode());
		System.out.println(context.getBean("number61", String.class).hashCode());
		System.out.println(context.getBean("number62", String.class).hashCode());
		System.out.println(context.getBean("number63", String.class).hashCode());
		System.out.println(context.getBean("number64", String.class).hashCode());
		System.out.println(context.getBean("number65", String.class).hashCode());
		System.out.println(context.getBean("number66", String.class).hashCode());
		System.out.println(context.getBean("number67", String.class).hashCode());
		System.out.println(context.getBean("number68", String.class).hashCode());
		System.out.println(context.getBean("number69", String.class).hashCode());
		System.out.println("number70:" + context.getBean("number70", String.class).hashCode());
		System.out.println(context.getBean("number71", String.class).hashCode());
		System.out.println(context.getBean("number72", String.class).hashCode());
		System.out.println(context.getBean("number73", String.class).hashCode());
		System.out.println(context.getBean("number74", String.class).hashCode());
		System.out.println(context.getBean("number75", String.class).hashCode());
		System.out.println(context.getBean("number76", String.class).hashCode());
		System.out.println(context.getBean("number77", String.class).hashCode());
		System.out.println(context.getBean("number78", String.class).hashCode());
		System.out.println(context.getBean("number79", String.class).hashCode());
		System.out.println("number80:" + context.getBean("number80", String.class).hashCode());
		System.out.println(context.getBean("number81", String.class).hashCode());
		System.out.println(context.getBean("number82", String.class).hashCode());
		System.out.println(context.getBean("number83", String.class).hashCode());
		System.out.println(context.getBean("number84", String.class).hashCode());
		System.out.println(context.getBean("number85", String.class).hashCode());
		System.out.println(context.getBean("number86", String.class).hashCode());
		System.out.println(context.getBean("number87", String.class).hashCode());
		System.out.println(context.getBean("number88", String.class).hashCode());
		System.out.println(context.getBean("number89", String.class).hashCode());
		System.out.println("number90:" + context.getBean("number90", String.class).hashCode());
		System.out.println(context.getBean("number91", String.class).hashCode());
		System.out.println(context.getBean("number92", String.class).hashCode());
		System.out.println(context.getBean("number93", String.class).hashCode());
		System.out.println(context.getBean("number94", String.class).hashCode());
		System.out.println(context.getBean("number95", String.class).hashCode());
		System.out.println(context.getBean("number96", String.class).hashCode());
		System.out.println(context.getBean("number97", String.class).hashCode());
		System.out.println(context.getBean("number91", String.class).hashCode());
		System.out.println(context.getBean("number92", String.class).hashCode());
		System.out.println(context.getBean("number93", String.class).hashCode());
		System.out.println(context.getBean("number94", String.class).hashCode());
		System.out.println(context.getBean("number95", String.class).hashCode());
		System.out.println(context.getBean("number96", String.class).hashCode());
		System.out.println(context.getBean("number97", String.class).hashCode());
		System.out.println(context.getBean("number91", String.class).hashCode());
		System.out.println(context.getBean("number92", String.class).hashCode());
		System.out.println(context.getBean("number93", String.class).hashCode());
		System.out.println(context.getBean("number94", String.class).hashCode());
		System.out.println(context.getBean("number95", String.class).hashCode());
		System.out.println(context.getBean("number96", String.class).hashCode());
		System.out.println(context.getBean("number97", String.class).hashCode());
		
		
		
		System.out.println("number98" + context.getBean("number98", String.class).hashCode());
		System.out.println("number99" + context.getBean("number99", String.class).hashCode());
		System.out.println("number100" + context.getBean("number100", String.class).hashCode());

	}

}
